"""initial schema

Revision ID: 999b2b4c587a
Revises: 
Create Date: 2026-04-09 09:53:18.934607
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '999b2b4c587a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_aliases',
    sa.Column('id', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('agent', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('agent_configs',
    sa.Column('id', sa.String(length=6), nullable=False),
    sa.Column('agent', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent', 'key', name='uq_agent_config_key')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('is_git_repo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('flows',
    sa.Column('id', sa.String(length=6), nullable=False),
    sa.Column('project_id', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_flow_project_name')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=6), nullable=False),
    sa.Column('project_id', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('FEATURE', 'FIX', 'REFACTOR', 'CHORE', name='tasktype'), nullable=True),
    sa.Column('default_flow_name', sa.String(length=255), nullable=True),
    sa.Column('task_status', sa.String(length=50), nullable=True),
    sa.Column('worktree_branch', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flow_steps',
    sa.Column('id', sa.String(length=6), nullable=False),
    sa.Column('flow_id', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('gates', sa.Text(), nullable=True),
    sa.Column('ifs', sa.Text(), nullable=True),
    sa.Column('agent_alias', sa.String(length=50), nullable=True),
    sa.Column('allow_max', sa.Boolean(), nullable=True),
    sa.Column('max_gate_retries', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_runs',
    sa.Column('id', sa.String(length=6), nullable=False),
    sa.Column('project_id', sa.String(length=6), nullable=False),
    sa.Column('task_id', sa.String(length=6), nullable=False),
    sa.Column('flow_name', sa.String(length=255), nullable=True),
    sa.Column('flow_snapshot', sa.Text(), nullable=True),
    sa.Column('current_step', sa.String(length=255), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('log_path', sa.Text(), nullable=True),
    sa.Column('user_prompt', sa.Text(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('steps_completed', sa.Text(), nullable=True),
    sa.Column('recovery_count', sa.Integer(), nullable=False),
    sa.Column('one_shot', sa.Boolean(), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('resume_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('step_runs',
    sa.Column('id', sa.String(length=6), nullable=False),
    sa.Column('run_id', sa.String(length=6), nullable=False),
    sa.Column('step_name', sa.String(length=255), nullable=False),
    sa.Column('step_position', sa.Integer(), nullable=False),
    sa.Column('flow_name', sa.String(length=255), nullable=False),
    sa.Column('agent', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('log_path', sa.Text(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('gate_failures', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['task_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('step_runs')
    op.drop_table('task_runs')
    op.drop_table('flow_steps')
    op.drop_table('tasks')
    op.drop_table('flows')
    op.drop_table('projects')
    op.drop_table('agent_configs')
    op.drop_table('agent_aliases')
    # ### end Alembic commands ###
